# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/cons.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blk_mem_gen_0_0/design_1_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_0 || ORIG_REF_NAME==design_1_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ov7670_capture_0_0/design_1_ov7670_capture_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ov7670_capture_0_0 || ORIG_REF_NAME==design_1_ov7670_capture_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blk_mem_gen_0_1/design_1_blk_mem_gen_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_1 || ORIG_REF_NAME==design_1_blk_mem_gen_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_control_0_1/design_1_control_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_control_0_1 || ORIG_REF_NAME==design_1_control_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_1to2_0_0/design_1_xbar_1to2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbar_1to2_0_0 || ORIG_REF_NAME==design_1_xbar_1to2_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ov7670_controller_0_1/design_1_ov7670_controller_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ov7670_controller_0_1 || ORIG_REF_NAME==design_1_ov7670_controller_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mux_2to1_0_3/design_1_mux_2to1_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_mux_2to1_0_3 || ORIG_REF_NAME==design_1_mux_2to1_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mux_2to1_1_1/design_1_mux_2to1_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_mux_2to1_1_1 || ORIG_REF_NAME==design_1_mux_2to1_1_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_slave_0_0/design_1_axi_slave_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_slave_0_0 || ORIG_REF_NAME==design_1_axi_slave_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_hdrvga_v2_0_1/design_1_hdrvga_v2_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_hdrvga_v2_0_1 || ORIG_REF_NAME==design_1_hdrvga_v2_0_1} -quiet] -quiet

# XDC: bd/design_1/design_1_ooc.xdc
