# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: k:/ECE532/prj/IP/camera_vga/camera_vga/camera_vga.srcs/sources_1/bd/design_1/ip/design_1_hdrvga_v2_0_1/design_1_hdrvga_v2_0_1.xci
# IP: The module: 'design_1_hdrvga_v2_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: k:/ECE532/prj/IP/camera_vga/camera_vga/camera_vga.srcs/sources_1/bd/design_1/ip/design_1_hdrvga_v2_0_1/constrs_1/imports/new/cons.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_hdrvga_v2_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: k:/ECE532/prj/IP/camera_vga/camera_vga/camera_vga.srcs/sources_1/bd/design_1/ip/design_1_hdrvga_v2_0_1/design_1_hdrvga_v2_0_1.xci
# IP: The module: 'design_1_hdrvga_v2_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: k:/ECE532/prj/IP/camera_vga/camera_vga/camera_vga.srcs/sources_1/bd/design_1/ip/design_1_hdrvga_v2_0_1/constrs_1/imports/new/cons.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_hdrvga_v2_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
