# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: k:/ECE532/prj/project/project.srcs/sources_1/bd/design_1/ip/design_1_ov7670_hdr_module_0_0/design_1_ov7670_hdr_module_0_0.xci
# IP: The module: 'design_1_ov7670_hdr_module_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: k:/ECE532/prj/project/ECE532/prj/IP/camera_vga/camera_vga/camera_vga.srcs/sources_1/bd/design_1/ip/design_1_blk_mem_gen_0_0/design_1_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_0 || ORIG_REF_NAME==design_1_blk_mem_gen_0_0} -quiet] -quiet

# IP: k:/ECE532/prj/project/ECE532/prj/IP/camera_vga/camera_vga/camera_vga.srcs/sources_1/bd/design_1/ip/design_1_xbar_1to2_0_0/design_1_xbar_1to2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbar_1to2_0_0 || ORIG_REF_NAME==design_1_xbar_1to2_0_0} -quiet] -quiet

# IP: k:/ECE532/prj/project/ECE532/prj/IP/camera_vga/camera_vga/camera_vga.srcs/sources_1/bd/design_1/ip/design_1_blk_mem_gen_0_1/design_1_blk_mem_gen_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_1 || ORIG_REF_NAME==design_1_blk_mem_gen_0_1} -quiet] -quiet

# IP: k:/ECE532/prj/project/ECE532/prj/IP/camera_vga/camera_vga/camera_vga.srcs/sources_1/bd/design_1/ip/design_1_axi_slave_0_0/design_1_axi_slave_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_slave_0_0 || ORIG_REF_NAME==design_1_axi_slave_0_0} -quiet] -quiet

# IP: k:/ECE532/prj/project/ECE532/prj/IP/camera_vga/camera_vga/camera_vga.srcs/sources_1/bd/design_1/ip/design_1_hdrvga_v2_0_1/design_1_hdrvga_v2_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_hdrvga_v2_0_1 || ORIG_REF_NAME==design_1_hdrvga_v2_0_1} -quiet] -quiet

# IP: k:/ECE532/prj/project/ECE532/prj/IP/camera_vga/camera_vga/camera_vga.srcs/sources_1/bd/design_1/ip/design_1_ov7670_capture_0_0/design_1_ov7670_capture_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ov7670_capture_0_0 || ORIG_REF_NAME==design_1_ov7670_capture_0_0} -quiet] -quiet

# IP: k:/ECE532/prj/project/ECE532/prj/IP/camera_vga/camera_vga/camera_vga.srcs/sources_1/bd/design_1/ip/design_1_control_0_1/design_1_control_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_control_0_1 || ORIG_REF_NAME==design_1_control_0_1} -quiet] -quiet

# IP: k:/ECE532/prj/project/ECE532/prj/IP/camera_vga/camera_vga/camera_vga.srcs/sources_1/bd/design_1/ip/design_1_ov7670_controller_0_1/design_1_ov7670_controller_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ov7670_controller_0_1 || ORIG_REF_NAME==design_1_ov7670_controller_0_1} -quiet] -quiet

# IP: k:/ECE532/prj/project/ECE532/prj/IP/camera_vga/camera_vga/camera_vga.srcs/sources_1/bd/design_1/ip/design_1_mux_2to1_0_3/design_1_mux_2to1_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_mux_2to1_0_3 || ORIG_REF_NAME==design_1_mux_2to1_0_3} -quiet] -quiet

# IP: k:/ECE532/prj/project/ECE532/prj/IP/camera_vga/camera_vga/camera_vga.srcs/sources_1/bd/design_1/ip/design_1_mux_2to1_1_1/design_1_mux_2to1_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_mux_2to1_1_1 || ORIG_REF_NAME==design_1_mux_2to1_1_1} -quiet] -quiet

# XDC: k:/ECE532/prj/project/ECE532/prj/IP/camera_vga/camera_vga/camera_vga.srcs/sources_1/bd/design_1/ip/design_1_blk_mem_gen_0_0/design_1_blk_mem_gen_0_0_ooc.xdc

# XDC: k:/ECE532/prj/project/ECE532/prj/IP/camera_vga/camera_vga/camera_vga.srcs/sources_1/bd/design_1/ip/design_1_blk_mem_gen_0_1/design_1_blk_mem_gen_0_1_ooc.xdc

# XDC: k:/ECE532/prj/project/ECE532/prj/IP/camera_vga/camera_vga/camera_vga.srcs/sources_1/bd/design_1/ip/design_1_hdrvga_v2_0_1/constrs_1/imports/new/cons.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_hdrvga_v2_0_1 || ORIG_REF_NAME==design_1_hdrvga_v2_0_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: k:/ECE532/prj/project/ECE532/prj/IP/camera_vga/camera_vga/camera_vga.srcs/constrs_1/new/cons.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_ov7670_hdr_module_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: k:/ECE532/prj/project/ECE532/prj/IP/camera_vga/camera_vga/camera_vga.srcs/sources_1/bd/design_1/design_1_ooc.xdc

# IP: k:/ECE532/prj/project/project.srcs/sources_1/bd/design_1/ip/design_1_ov7670_hdr_module_0_0/design_1_ov7670_hdr_module_0_0.xci
# IP: The module: 'design_1_ov7670_hdr_module_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: k:/ECE532/prj/project/ECE532/prj/IP/camera_vga/camera_vga/camera_vga.srcs/sources_1/bd/design_1/ip/design_1_blk_mem_gen_0_0/design_1_blk_mem_gen_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_0 || ORIG_REF_NAME==design_1_blk_mem_gen_0_0} -quiet] -quiet

# IP: k:/ECE532/prj/project/ECE532/prj/IP/camera_vga/camera_vga/camera_vga.srcs/sources_1/bd/design_1/ip/design_1_xbar_1to2_0_0/design_1_xbar_1to2_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbar_1to2_0_0 || ORIG_REF_NAME==design_1_xbar_1to2_0_0} -quiet] -quiet

# IP: k:/ECE532/prj/project/ECE532/prj/IP/camera_vga/camera_vga/camera_vga.srcs/sources_1/bd/design_1/ip/design_1_blk_mem_gen_0_1/design_1_blk_mem_gen_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_1 || ORIG_REF_NAME==design_1_blk_mem_gen_0_1} -quiet] -quiet

# IP: k:/ECE532/prj/project/ECE532/prj/IP/camera_vga/camera_vga/camera_vga.srcs/sources_1/bd/design_1/ip/design_1_axi_slave_0_0/design_1_axi_slave_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_slave_0_0 || ORIG_REF_NAME==design_1_axi_slave_0_0} -quiet] -quiet

# IP: k:/ECE532/prj/project/ECE532/prj/IP/camera_vga/camera_vga/camera_vga.srcs/sources_1/bd/design_1/ip/design_1_hdrvga_v2_0_1/design_1_hdrvga_v2_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_hdrvga_v2_0_1 || ORIG_REF_NAME==design_1_hdrvga_v2_0_1} -quiet] -quiet

# IP: k:/ECE532/prj/project/ECE532/prj/IP/camera_vga/camera_vga/camera_vga.srcs/sources_1/bd/design_1/ip/design_1_ov7670_capture_0_0/design_1_ov7670_capture_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ov7670_capture_0_0 || ORIG_REF_NAME==design_1_ov7670_capture_0_0} -quiet] -quiet

# IP: k:/ECE532/prj/project/ECE532/prj/IP/camera_vga/camera_vga/camera_vga.srcs/sources_1/bd/design_1/ip/design_1_control_0_1/design_1_control_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_control_0_1 || ORIG_REF_NAME==design_1_control_0_1} -quiet] -quiet

# IP: k:/ECE532/prj/project/ECE532/prj/IP/camera_vga/camera_vga/camera_vga.srcs/sources_1/bd/design_1/ip/design_1_ov7670_controller_0_1/design_1_ov7670_controller_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ov7670_controller_0_1 || ORIG_REF_NAME==design_1_ov7670_controller_0_1} -quiet] -quiet

# IP: k:/ECE532/prj/project/ECE532/prj/IP/camera_vga/camera_vga/camera_vga.srcs/sources_1/bd/design_1/ip/design_1_mux_2to1_0_3/design_1_mux_2to1_0_3.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_mux_2to1_0_3 || ORIG_REF_NAME==design_1_mux_2to1_0_3} -quiet] -quiet

# IP: k:/ECE532/prj/project/ECE532/prj/IP/camera_vga/camera_vga/camera_vga.srcs/sources_1/bd/design_1/ip/design_1_mux_2to1_1_1/design_1_mux_2to1_1_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_mux_2to1_1_1 || ORIG_REF_NAME==design_1_mux_2to1_1_1} -quiet] -quiet

# XDC: k:/ECE532/prj/project/ECE532/prj/IP/camera_vga/camera_vga/camera_vga.srcs/sources_1/bd/design_1/ip/design_1_blk_mem_gen_0_0/design_1_blk_mem_gen_0_0_ooc.xdc

# XDC: k:/ECE532/prj/project/ECE532/prj/IP/camera_vga/camera_vga/camera_vga.srcs/sources_1/bd/design_1/ip/design_1_blk_mem_gen_0_1/design_1_blk_mem_gen_0_1_ooc.xdc

# XDC: k:/ECE532/prj/project/ECE532/prj/IP/camera_vga/camera_vga/camera_vga.srcs/sources_1/bd/design_1/ip/design_1_hdrvga_v2_0_1/constrs_1/imports/new/cons.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_hdrvga_v2_0_1 || ORIG_REF_NAME==design_1_hdrvga_v2_0_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: k:/ECE532/prj/project/ECE532/prj/IP/camera_vga/camera_vga/camera_vga.srcs/constrs_1/new/cons.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_ov7670_hdr_module_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: k:/ECE532/prj/project/ECE532/prj/IP/camera_vga/camera_vga/camera_vga.srcs/sources_1/bd/design_1/design_1_ooc.xdc
